### ISSUE TITLE
Option --force for production in CI system

### ISSUE THREAD

**Issue by ntvsx193** [marlek/laravel-automigrate#2]
Hello!
I'm using in CI system Teamcity.
Command`php artisan automigrate` don't  run whitout answer `yes`.
What about option `--force`?
Thanks :)

**Comment by marlek** [comment]
Hi,
The `automigrate` command itself doesn't ask questions, it seams like your app in CI is in production mode. Laravel recognizes this and asks if you're sure you want to run the command in production environment. This is not recommended.

If you're sure you want to `automigrate` in this environment you can always call the command with:
```
yes | php artisan automigrate
```
which will answer with `yes` to all questions asked by the command.

**Comment by ntvsx193** [comment]
Oh, thank you very much!
